/*
 * generated by Xtext 2.26.0
 */
package org.itlingo.rsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.itlingo.rsl.RslRuntimeModule;
import org.itlingo.rsl.RslStandaloneSetup;
import org.itlingo.rsl.ide.diagram.RslDiagramModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RslIdeSetup extends RslStandaloneSetup {

	@Override
	public Injector createInjector() {
		System.out.println("injected oi oi");
		return Guice.createInjector(Modules2.mixin(new RslRuntimeModule(), new RslIdeModule(), new RslDiagramModule()));
	}
	
}
