/*
 * generated by Xtext 2.26.0
 */
package org.itlingo.rsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RslRuntimeModule extends AbstractRslRuntimeModule {
}
