/*
 * generated by Xtext 2.26.0
 */
package org.itlingo.rsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RslStandaloneSetup extends RslStandaloneSetupGenerated {

	public static void doSetup() {
		new RslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
